### ISSUE TITLE
[Question]  - migrations and factory ?

### ISSUE THREAD

**Issue by Nejcc** [TimoKoerber/laravel-one-time-operations#1]
Why you have migrations and factory in completly different folders  like in model in this case  why this is not stored on same level like laravel have  migrations/seeds/factories ?

**Comment by TimoKoerber** [comment]
You got a point! The reason is creative freedom, I guess :D 
I kinda like storing the factory so close to the model since a factory does not work without a model. and since other packages also take some freedom when setting up the directory structure, I just did the same ;)

**Comment by Nejcc** [comment]
Oh i see, well as a software architect i look at things from different perspectives; things that are must for app tu run - need to be there, things that are used as one time, support the core/application or run in isolation is good practice to use outside the app scope. there are several reasons why from security to layering the scopes in proper structural architecture :)  I completely understand you, a few years ago, I myself had my own style of organizing projects/packages. However, with "Open source projects" it is always necessary to take into account code standards or be a part of a community, according to which most people work in this way, it is also much easier to build new visions and interest in the project :)

**Comment by TimoKoerber** [comment]
You are correct! Let's do it by the book. I will change it with the next release!

**Comment by TimoKoerber** [comment]
fixed with latest release 1.0.5
