### ISSUE TITLE
Overriding stubs

### ISSUE THREAD

**Issue by Tklaversma** [TimoKoerber/laravel-one-time-operations#13]
It's currently not possible to override the stubs. I would expect that this would work the same as with the default Laravel stubs, by adding the already existing stub files into `/stubs/...` and make the adjustments as we like.

Could this be added :)?

**Comment by Orrison** [comment]
This would be very useful and go a long way in improving the usability/safe malleability of the package.

**Comment by TimoKoerber** [comment]
@Tklaversma This is a very good idea! I just provided this feature! Thanks for the Input!
