### ISSUE TITLE
[Enhancement] Allow dispatching of multiple jobs / batch.

### ISSUE THREAD

**Issue by danmatthews** [TimoKoerber/laravel-one-time-operations#19]
I might drop a PR for this eventually, but it's something we'd love - the ability to drop a chain / batch of jobs or operations that would ALL need to run for the operation to be complete.

The use case:
We found that migrating 500k rows was timing out on a single job, and i don't like to have a single queue that has unlimited or a super-long timeout as it can cause problems with stuck jobs, so being able to create a "batch operation" would be cool as heck, even if it just was as simple as implemented a `BatchOperation` interface that defined a "singleOperation" function or similar.

Then those could be dispatched as callables on the queue using a custom job, OR dispatched as closures.

Then that would allow you to specify a "final" job that maybe does some tidying up with a "finally()" method or similar.

All defined within one file similar to how it is now, but gives more flexibility.

Will have a look at a PR if i can get some time IF you like the idea?

**Comment by TimoKoerber** [comment]
I don't think, that I'm going to implement this, because it would be too much overhead just to implement this specific use case. 
The thought behind this package is just starting an operation automatically after deployment. What happens after this "jump start" shouldn't be the job of this package. 
You can still use the package just to start the Batch process, and you basically have the same result, right?

``` 
// 2023_06_16_135513_start_batch_operation.php

return new class extends OneTimeOperation
{
    protected bool $async = false;

    public function process(): void
    {
        Bus::batch([
            //
        ])->then(function (Batch $batch) {
            // 
        })->catch(function (Batch $batch, Throwable $e) {
            // 
        })->finally(function (Batch $batch) {
            // 
        })->dispatch();
    }
};
```

**Comment by danmatthews** [comment]
Yeah, and this is basically what we're doing now!

My idea is probably because of our use case, and that's not something you maybe want to cover with this package, but I basically see it as a way of:

"quickly running one-time operations, or small data migrations quickly on deployment."

but possibly also, imagine being able to run larger operations like larger data migrations using batches and ALSO being able to Feature-flag code behind if the batch/operation has completed.

So you:

- Push your code to production ,it starts the migration queued operation.
- You have some code in your application that relies on the "new" structure of data, so you have a guard statement like `if (Operation::isComplete('operation-name')) {` to prevent users from accessing it until the migration has been ran.
- OR you could integrate with Laravel Pennant to define a feature that is true/false depending on the operation status, something like: `Feature::enabled('operation:operation-name') ? true : false` etc.

To be fair: you could also do this with Atomic Locks already, but the package bringing it together would provide a lot of convenience.

might be out of the scope of what you want to provide, but also potentially something very cool and convenient.

**Comment by TimoKoerber** [comment]
> might be out of the scope of what you want to provide

Yes, exactly! :D 

It's kinda cool, that all the users have so many creative ideas on how this package could be expanded. But I want to keep it simple and lean and focus on the USP of this package. 

But feel free to create a fork and realize your idea ;)

**Comment by danmatthews** [comment]
No problem man, thanks for chatting it out with me. Will close this now.
