### ISSUE TITLE
What if I want to run an operation as part of a data migration?

### ISSUE THREAD

**Issue by abbluiz** [TimoKoerber/laravel-one-time-operations#2]
Sometimes I want to run an operation as part of a migration (before, during or after a specific migration). This package only supports running operations after all migrations are run, or before all migrations are run.

An example would be if I want to change the way data is stored, it needs to be an intermediate step to migrate the data, otherwise old data is lost.

**Comment by aou24** [comment]
I mean, you can make it however you need it.
For example in an operation: 
1. get the data from the database
2. execute single migration: php artisan migrate --path=/database/migrations/my_migration.php 
or execute all migrations
3. put the data back into the database. 

So the old data will not be lost.

NB To execute the command lines, you can use e.g. the Process component of Symfony.

**Comment by TimoKoerber** [comment]
That sounds like a very very specific use case 😅 I thought of something like this but this would have blown up that package unnecessarily. KISS! (Keep it simple and stupid!) 😉
