### ISSUE TITLE
Spelling mistake in synchronously and similar words

### ISSUE THREAD

**Issue by Glenn-townsend-music** [TimoKoerber/laravel-one-time-operations#22]
There are a lot of instances of `syncronously` and `asyncronously` in this repo. They should be `synchronously` and `asynchronously`.

I know it's not a big deal, but my IDE is highlighting them as spelling mistakes.

**Comment by JHWelch** [comment]
There is a fix for this in #18, but I have not seen movement on this repo since April.

**Comment by Glenn-townsend-music** [comment]
Thanks, @JHWelch . I was carefull to look through all the open issues but I didn't think to look at the PRs :facepalm:  I'll close my issue now.

**Comment by JHWelch** [comment]
No worries, and honestly you could keep the issue opened, the Issue is still around, you could just link it to the PR and mark it fixed when it actually gets fixed.
