### ISSUE TITLE
[Enhancement] - Rename operations:make to make:operations for Better Consistency

### ISSUE THREAD

**Issue by herovish143** [TimoKoerber/laravel-one-time-operations#40]
## Issue:
Currently, the command to create a new operation is **operations:make**. It would be more suitable and consistent with Laravel's naming conventions to rename it to **_make:operations_**.

In Laravel, most of the artisan commands follow a make:resource structure (e.g., **make:model**, **make:controller**), which keeps things organized and intuitive. Renaming this command would align it better with Laravel's overall structure.

## Proposed Solution:

Rename the operations:make command to make:operations to follow the standard Laravel command format.

### PR
https://github.com/TimoKoerber/laravel-one-time-operations/pull/41

Thanks & Happy Coding ❤️

**Comment by nathanjansen** [comment]
Can be closed now, see: https://github.com/TimoKoerber/laravel-one-time-operations/releases/tag/1.4.4

**Comment by herovish143** [comment]
Yeah, sure close it.

Thanks ❤️ @TimoKoerber @nathanjansen
